"use client";

import { useState, useEffect, useMemo } from "react";
import { X, Truck, QrCode, Check, Clock, ChevronDown, UserPlus, User, Printer } from "lucide-react";
import { type FactoryRequest, type DispatchItem } from "@/lib/mock/factoryRequests";
import { useRequestsDB } from "@/lib/db/requests";
import { drivers, type Driver } from "@/lib/mock/drivers";
import { Card } from "@/components/ui/Card";
import { cn } from "@/lib/utils";

/** QR validity window — branch must scan within this time after dispatch. */
const QR_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

/** Build the structured payload encoded into the QR. */
export function buildQRPayload(req: FactoryRequest): string {
  const payload = {
    order_id: req.requestNumber,
    token: req.dispatchToken ?? "",
    issued_at: req.dispatchedAtISO ?? new Date().toISOString(),
    expires_in: QR_TTL_MS / 1000,
  };
  return JSON.stringify(payload);
}

interface DispatchPanelProps {
  request: FactoryRequest;
  onClose: () => void;
}

/* ── Real, scannable QR generated by qrcode-generator (loaded once per
 * session from a CDN). The matrix is rendered as one path which keeps
 * the SVG lean even at large sizes. */

let qrLib: any | null = null;

function MockQR({ value }: { value: string }) {
  const [matrix, setMatrix] = useState<{ size: number; modules: boolean[][] } | null>(null);
  const [error, setError] = useState<string>("");

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        if (!qrLib) {
          const mod: any = await import(/* webpackIgnore: true */ "https://esm.sh/qrcode-generator@1.4.4");
          qrLib = mod.default || mod;
        }
        // Type "M" error correction = ~15% damage tolerance; auto type number.
        const qr = qrLib(0, "M");
        qr.addData(value);
        qr.make();
        const size = qr.getModuleCount();
        const modules: boolean[][] = [];
        for (let y = 0; y < size; y++) {
          const row: boolean[] = [];
          for (let x = 0; x < size; x++) row.push(qr.isDark(y, x));
          modules.push(row);
        }
        if (!cancelled) setMatrix({ size, modules });
      } catch (err: any) {
        if (!cancelled) setError(err?.message ?? "تعذّر توليد الكود");
      }
    })();
    return () => { cancelled = true; };
  }, [value]);

  return (
    <div className="p-3 bg-white rounded-lg border border-border-subtle inline-block">
      {matrix ? (
        <svg
          viewBox={`0 0 ${matrix.size} ${matrix.size}`}
          shapeRendering="crispEdges"
          className="w-44 h-44"
          aria-label="QR code"
        >
          <rect width={matrix.size} height={matrix.size} fill="#fff" />
          {matrix.modules.map((row, y) =>
            row.map((on, x) => on ? (
              <rect key={`${x}-${y}`} x={x} y={y} width={1} height={1} fill="#000" />
            ) : null)
          )}
        </svg>
      ) : (
        <div className="w-44 h-44 flex items-center justify-center text-[11px] text-text-tertiary">
          {error ? error : "جاري توليد الكود..."}
        </div>
      )}
    </div>
  );
}

export function DispatchPanel({ request, onClose }: DispatchPanelProps) {
  const { dispatchOrder, requests } = useRequestsDB();
  // Read the live version of this request — needed in the QR phase to pick
  // up the dispatchToken + dispatchedAtISO that were just generated.
  const liveRequest = requests.find((r) => r.id === request.id) ?? request;

  // Quantities are finalized at approval time (factory edits in the
  // request detail before approving), so the dispatch panel only reads
  // them — no edit controls here.
  const dispatchItems: DispatchItem[] = useMemo(() => (
    request.items.map((it) => ({
      catalogId: it.catalogId,
      name: it.name,
      unit: it.unit,
      requestedQty: it.requestedQty,
      dispatchedQty: it.approvedQty ?? it.requestedQty,
    }))
  ), [request.items]);

  const [note, setNote] = useState("");
  const [driverMode, setDriverMode] = useState<"existing" | "new">("existing");
  const [selectedDriverId, setSelectedDriverId] = useState<string>("");
  const [driverName, setDriverName] = useState("");
  const [driverPhone, setDriverPhone] = useState("");
  const [driverNationalId, setDriverNationalId] = useState("");
  const [driverVehicleNumber, setDriverVehicleNumber] = useState("");
  const [driverVehicleType, setDriverVehicleType] = useState("");
  const [driverPickerOpen, setDriverPickerOpen] = useState(false);
  const [phase, setPhase] = useState<"edit" | "qr">("edit");

  const selectedDriver: Driver | undefined = useMemo(
    () => drivers.find((d) => d.id === selectedDriverId),
    [selectedDriverId]
  );

  const driverReady = driverMode === "existing"
    ? !!selectedDriver
    : driverName.trim().length > 0 && driverPhone.trim().length > 0;

  function pickDriver(d: Driver) {
    setSelectedDriverId(d.id);
    setDriverPickerOpen(false);
  }

  function switchToNewDriver() {
    setDriverMode("new");
    setSelectedDriverId("");
    setDriverName("");
    setDriverPhone("");
    setDriverNationalId("");
    setDriverVehicleNumber("");
    setDriverVehicleType("");
  }

  function switchToExistingDriver() {
    setDriverMode("existing");
    setDriverName("");
    setDriverPhone("");
    setDriverNationalId("");
    setDriverVehicleNumber("");
    setDriverVehicleType("");
  }

  function handleDispatch() {
    const driverPayload = driverMode === "existing" && selectedDriver ? {
      id:            selectedDriver.id,
      name:          selectedDriver.name,
      phone:         selectedDriver.phone,
      nationalId:    selectedDriver.nationalId,
      vehicleNumber: selectedDriver.vehicleNumber,
      vehicleType:   selectedDriver.vehicleType,
    } : {
      name:          driverName.trim()       || undefined,
      phone:         driverPhone.trim()      || undefined,
      nationalId:    driverNationalId.trim() || undefined,
      vehicleNumber: driverVehicleNumber.trim() || undefined,
      vehicleType:   driverVehicleType.trim()   || undefined,
    };
    dispatchOrder(request.id, dispatchItems, note || undefined, driverPayload);
    setPhase("qr");
  }

  return (
    <>
      <div className="fixed inset-0 z-40 bg-black/40 backdrop-blur-[2px]" onClick={onClose} />
      <aside className="fixed top-0 right-0 bottom-0 z-50 w-full max-w-[480px] bg-bg-canvas border-l border-border-subtle shadow-2xl flex flex-col"
        style={{ animation: "slideInRight 280ms cubic-bezier(0.16,1,0.3,1)" }}>

        {/* Header */}
        <header className="shrink-0 px-5 py-4 border-b border-border-subtle flex items-center justify-between gap-3">
          <div>
            <p className="text-[10px] tracking-[0.18em] uppercase text-text-tertiary">DISPATCH ORDER</p>
            <h2 className="text-base font-bold tracking-tight mt-0.5">
              {phase === "qr" ? "جاهز للإرسال" : "تجهيز الطلب للإرسال"}
            </h2>
            <p className="text-[11px] text-text-tertiary mt-0.5">{request.requestNumber} · {request.branchName}</p>
          </div>
          <button type="button" onClick={onClose}
            className="w-9 h-9 rounded-sm flex items-center justify-center text-text-tertiary hover:text-text-primary hover:bg-bg-surface-raised transition-all">
            <X className="w-4 h-4" strokeWidth={2} />
          </button>
        </header>

        {phase === "edit" ? (
          <>
            <div className="flex-1 overflow-y-auto">
              {/* Items — read-only, qty already finalized at approval */}
              <div className="px-5 pt-4 pb-2">
                <p className="text-[10px] tracking-[0.16em] uppercase text-text-tertiary mb-3">
                  الأصناف المُرسلة
                </p>
                <div className="space-y-2">
                  {dispatchItems.map((it) => (
                    <div
                      key={it.catalogId}
                      className="flex items-center gap-3 rounded-md border border-border-subtle bg-bg-surface px-3 py-2.5"
                    >
                      <div className="flex-1 min-w-0">
                        <p className="text-xs font-medium truncate">{it.name}</p>
                      </div>
                      <p className="text-sm font-bold tabular tracking-tight shrink-0">
                        {it.dispatchedQty}
                        <span className="text-[10px] text-text-tertiary font-normal mr-1">{it.unit}</span>
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Driver + Note */}
              <div className="px-5 pt-4 pb-4 space-y-4">
                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <label className="block text-[10px] tracking-[0.16em] uppercase text-text-tertiary">السائق</label>
                    <button
                      type="button"
                      onClick={driverMode === "existing" ? switchToNewDriver : switchToExistingDriver}
                      className="inline-flex items-center gap-1 text-[11px] font-medium text-brand-primary hover:underline"
                    >
                      {driverMode === "existing" ? (
                        <>
                          <UserPlus className="w-3 h-3" strokeWidth={2} />
                          سائق جديد (مش مسجل)
                        </>
                      ) : (
                        <>
                          <User className="w-3 h-3" strokeWidth={2} />
                          اختر من المسجلين
                        </>
                      )}
                    </button>
                  </div>

                  {driverMode === "existing" ? (
                    <div className="relative">
                      <button
                        type="button"
                        onClick={() => setDriverPickerOpen((v) => !v)}
                        className={cn(
                          "w-full h-10 px-3 rounded-sm text-sm bg-bg-surface border outline-none tracking-tight transition-all",
                          "flex items-center justify-between",
                          driverPickerOpen ? "border-brand-primary" : "border-border hover:border-border-strong",
                          !selectedDriver && "text-text-tertiary"
                        )}
                      >
                        <span className="truncate">
                          {selectedDriver ? selectedDriver.name : "اختر سائقاً من القائمة"}
                        </span>
                        <ChevronDown className={cn("w-4 h-4 shrink-0 transition-transform", driverPickerOpen && "rotate-180")} strokeWidth={2} />
                      </button>
                      {driverPickerOpen && (
                        <div className="absolute z-10 mt-1 w-full max-h-60 overflow-y-auto rounded-sm border border-border bg-bg-surface shadow-lg">
                          {drivers.map((d) => {
                            const isSelected = d.id === selectedDriverId;
                            const statusLabel =
                              d.status === "available" ? "متاح" :
                              d.status === "on-route"  ? "في رحلة" : "خارج الدوام";
                            const statusColor =
                              d.status === "available" ? "bg-status-success" :
                              d.status === "on-route"  ? "bg-status-warning" : "bg-text-tertiary";
                            return (
                              <button
                                type="button"
                                key={d.id}
                                onClick={() => pickDriver(d)}
                                className={cn(
                                  "w-full px-3 py-2.5 flex items-start gap-2.5 text-right border-b border-border-subtle last:border-0 transition-colors",
                                  isSelected ? "bg-brand-primary/10" : "hover:bg-bg-surface-raised"
                                )}
                              >
                                <span className={cn("w-1.5 h-1.5 rounded-full mt-1.5 shrink-0", statusColor)} aria-hidden />
                                <div className="flex-1 min-w-0">
                                  <p className="text-sm font-medium tracking-tight truncate">{d.name}</p>
                                  <p className="text-[11px] text-text-tertiary tabular truncate">
                                    {d.vehicleType} · {d.vehicleNumber} · {d.phone}
                                  </p>
                                </div>
                                <span className="text-[10px] text-text-tertiary shrink-0 mt-0.5">{statusLabel}</span>
                              </button>
                            );
                          })}
                        </div>
                      )}

                      {selectedDriver && (
                        <div className="mt-2 rounded-sm border border-border-subtle bg-bg-surface-raised/40 p-3 grid grid-cols-2 gap-2 text-[11px]">
                          <DriverField label="رقم العربية" value={`${selectedDriver.vehicleType} · ${selectedDriver.vehicleNumber}`} />
                          <DriverField label="رقم التليفون" value={selectedDriver.phone} />
                          <DriverField label="الرقم القومي" value={selectedDriver.nationalId} className="col-span-2" />
                        </div>
                      )}
                    </div>
                  ) : (
                    <div className="space-y-2">
                      <input
                        value={driverName}
                        onChange={(e) => setDriverName(e.target.value)}
                        placeholder="اسم السائق"
                        className="w-full h-10 px-3 rounded-sm text-sm bg-bg-surface border border-border focus:border-brand-primary outline-none tracking-tight transition-all"
                      />
                      <div className="grid grid-cols-2 gap-2">
                        <input
                          value={driverVehicleType}
                          onChange={(e) => setDriverVehicleType(e.target.value)}
                          placeholder="نوع العربية"
                          className="h-10 px-3 rounded-sm text-sm bg-bg-surface border border-border focus:border-brand-primary outline-none tracking-tight transition-all"
                        />
                        <input
                          value={driverVehicleNumber}
                          onChange={(e) => setDriverVehicleNumber(e.target.value)}
                          placeholder="رقم العربية"
                          className="h-10 px-3 rounded-sm text-sm bg-bg-surface border border-border focus:border-brand-primary outline-none tracking-tight tabular transition-all"
                        />
                      </div>
                      <input
                        value={driverPhone}
                        onChange={(e) => setDriverPhone(e.target.value)}
                        placeholder="رقم التليفون"
                        inputMode="tel"
                        className="w-full h-10 px-3 rounded-sm text-sm bg-bg-surface border border-border focus:border-brand-primary outline-none tracking-tight tabular transition-all"
                      />
                      <input
                        value={driverNationalId}
                        onChange={(e) => setDriverNationalId(e.target.value)}
                        placeholder="الرقم القومي (14 رقم)"
                        inputMode="numeric"
                        maxLength={14}
                        className="w-full h-10 px-3 rounded-sm text-sm bg-bg-surface border border-border focus:border-brand-primary outline-none tracking-tight tabular transition-all"
                      />
                    </div>
                  )}
                </div>

                <div>
                  <label className="block text-[10px] tracking-[0.16em] uppercase text-text-tertiary mb-1.5">
                    ملاحظة للفرع (اختياري)
                  </label>
                  <textarea
                    value={note}
                    onChange={(e) => setNote(e.target.value)}
                    placeholder="مثال: تأخر الإرسال نصف ساعة بسبب الطقس"
                    rows={3}
                    className="w-full px-3 py-2.5 rounded-sm text-sm bg-bg-surface border border-border focus:border-brand-primary outline-none tracking-tight resize-none transition-all placeholder:text-text-tertiary"
                  />
                </div>
              </div>
            </div>

            <div className="shrink-0 px-5 py-4 border-t border-border-subtle bg-bg-surface/60 flex gap-2">
              <button type="button" onClick={onClose}
                className="flex-1 h-11 rounded-sm border border-border bg-bg-surface text-text-secondary text-sm font-medium hover:border-border-strong transition-colors">
                إلغاء
              </button>
              <button
                type="button"
                onClick={handleDispatch}
                disabled={!driverReady}
                title={!driverReady ? "اختر سائقاً أو أدخل بياناته" : ""}
                className="flex-[2] h-11 rounded-sm bg-brand-primary text-text-on-brand text-sm font-medium inline-flex items-center justify-center gap-2 hover:bg-brand-primary-hover disabled:opacity-40 disabled:cursor-not-allowed active:scale-[0.98] transition-all"
              >
                <Truck className="w-4 h-4" strokeWidth={2} />
                إرسال الطلب للفرع
              </button>
            </div>
          </>
        ) : (
          /* QR phase */
          <>
          <div className="flex-1 flex flex-col items-center justify-start px-8 py-6 text-center space-y-5 overflow-y-auto">
            <div className="w-14 h-14 rounded-full bg-status-success/15 text-status-success flex items-center justify-center">
              <Check className="w-7 h-7" strokeWidth={2} />
            </div>
            <div>
              <h3 className="text-lg font-bold tracking-tight">تم إرسال الطلب!</h3>
              <p className="text-sm text-text-secondary mt-1 leading-relaxed">
                الطلب {request.requestNumber} في الطريق إلى {request.branchName}
              </p>
            </div>

            <div className="py-2 space-y-3">
              <p className="text-[11px] tracking-[0.14em] uppercase text-text-tertiary">
                <QrCode className="w-3.5 h-3.5 inline-block mr-1" strokeWidth={1.75} />
                أعطِ هذا الكود للسائق
              </p>
              <MockQR value={buildQRPayload(liveRequest)} />
              <div className="flex items-center justify-center gap-2 text-[11px] text-text-tertiary tabular">
                <span>الكود:</span>
                <code className="px-2 py-0.5 rounded bg-bg-surface-raised text-text-secondary font-mono tracking-wider">
                  {liveRequest.dispatchToken ?? "—"}
                </code>
              </div>
              <ExpiryCountdown issuedAtISO={liveRequest.dispatchedAtISO} />
            </div>

            {liveRequest.driverName && (
              <Card padding="sm" className="w-full text-right space-y-1.5">
                <p className="text-[10px] tracking-[0.16em] uppercase text-text-tertiary">السائق</p>
                <p className="text-sm font-bold tracking-tight">{liveRequest.driverName}</p>
                <div className="grid grid-cols-2 gap-1.5 pt-1.5 border-t border-border-subtle">
                  {(liveRequest.driverVehicleType || liveRequest.driverVehicleNumber) && (
                    <DriverField
                      label="رقم العربية"
                      value={[liveRequest.driverVehicleType, liveRequest.driverVehicleNumber].filter(Boolean).join(" · ")}
                    />
                  )}
                  {liveRequest.driverPhone && <DriverField label="التليفون" value={liveRequest.driverPhone} />}
                  {liveRequest.driverNationalId && (
                    <DriverField label="الرقم القومي" value={liveRequest.driverNationalId} className="col-span-2" />
                  )}
                </div>
              </Card>
            )}

            {/* Action buttons */}
            <div className="w-full space-y-2 pb-2">
              <button
                type="button"
                onClick={() => {
                  const printArea = document.getElementById("qr-print-area");
                  if (!printArea) { window.print(); return; }
                  // Inject print CSS temporarily
                  const style = document.createElement("style");
                  style.setAttribute("data-qr-print", "1");
                  style.textContent = [
                    "@media print {",
                    "  body > *:not(#qr-print-area) { display: none !important; }",
                    "  #qr-print-area {",
                    "    display: block !important; position: fixed; inset: 0;",
                    "    background: white; padding: 32px; direction: rtl;",
                    "    font-family: system-ui, sans-serif;",
                    "  }",
                    "}",
                  ].join("\n");
                  document.head.appendChild(style);
                  printArea.classList.remove("hidden");
                  window.print();
                  printArea.classList.add("hidden");
                  document.querySelector("[data-qr-print]")?.remove();
                }}
                className="w-full h-11 rounded-sm border border-border-strong bg-bg-surface text-text-primary text-sm font-medium inline-flex items-center justify-center gap-2 hover:bg-bg-surface-raised transition-all active:scale-[0.98]"
              >
                <Printer className="w-4 h-4" strokeWidth={1.75} />
                طباعة QR Code للسائق
              </button>
              <button
                type="button"
                onClick={onClose}
                className="w-full h-11 rounded-sm bg-brand-primary text-text-on-brand text-sm font-medium inline-flex items-center justify-center gap-2 hover:bg-brand-primary-hover transition-all active:scale-[0.98]"
              >
                <Check className="w-4 h-4" strokeWidth={2.5} />
                السائق أخذ الكود · تم
              </button>
            </div>
          </div>

          {/* Hidden print area — CSS is injected by the print button's onClick */}
          <div id="qr-print-area" className="hidden">
            <div style={{ textAlign: "center", padding: "16px" }}>
              <p style={{ fontSize: "11px", letterSpacing: "0.15em", textTransform: "uppercase", color: "#888", marginBottom: "4px" }}>
                DISPATCH ORDER · QR CODE
              </p>
              <h2 style={{ fontSize: "22px", fontWeight: "bold", margin: "0 0 4px" }}>
                {liveRequest.requestNumber}
              </h2>
              <p style={{ fontSize: "13px", color: "#555", marginBottom: "20px" }}>
                {liveRequest.branchName} · {liveRequest.dispatchedAt}
              </p>

              {/* QR re-rendered for print */}
              <div style={{ display: "flex", justifyContent: "center", marginBottom: "12px" }}>
                <MockQR value={buildQRPayload(liveRequest)} />
              </div>

              <p style={{ fontSize: "12px", color: "#444", marginBottom: "4px" }}>
                الكود الأمني:&nbsp;
                <strong style={{ fontFamily: "monospace", letterSpacing: "0.1em" }}>
                  {liveRequest.dispatchToken}
                </strong>
              </p>

              {liveRequest.driverName && (
                <p style={{ fontSize: "12px", color: "#444", marginTop: "8px" }}>
                  السائق: <strong>{liveRequest.driverName}</strong>
                  {liveRequest.driverVehicleNumber && ` · ${liveRequest.driverVehicleType ?? ""} ${liveRequest.driverVehicleNumber}`}
                </p>
              )}

              <hr style={{ margin: "16px 0", borderColor: "#ddd" }} />
              <p style={{ fontSize: "11px", color: "#999" }}>
                الطلب في الطريق · يُمسح هذا الكود عند الاستلام · الصلاحية 24 ساعة
              </p>
            </div>
          </div>
          </>
        )}
      </aside>
    </>
  );
}

/* ── Compact two-line label/value cell used in driver summary ────────────── */
function DriverField({ label, value, className }: { label: string; value: string; className?: string }) {
  return (
    <div className={cn("min-w-0", className)}>
      <p className="text-[10px] text-text-tertiary tracking-tight">{label}</p>
      <p className="text-xs font-medium tabular tracking-tight truncate">{value}</p>
    </div>
  );
}

/* ── Live countdown showing time until QR expires ────────────────────────── */
function ExpiryCountdown({ issuedAtISO }: { issuedAtISO?: string }) {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(id);
  }, []);

  const issued = issuedAtISO ? new Date(issuedAtISO).getTime() : now;
  const remaining = Math.max(0, issued + QR_TTL_MS - now);
  const expired = remaining === 0;
  const hours    = Math.floor(remaining / 3_600_000);
  const minutes  = Math.floor((remaining % 3_600_000) / 60_000);
  const seconds  = Math.floor((remaining % 60_000) / 1000);

  if (expired) {
    return (
      <p className="inline-flex items-center gap-1.5 text-[11px] text-status-danger font-medium">
        <Clock className="w-3 h-3" strokeWidth={2} />
        انتهت صلاحية الكود — أنشئ كود جديد
      </p>
    );
  }
  return (
    <p className="inline-flex items-center gap-1.5 text-[11px] text-text-tertiary tabular">
      <Clock className="w-3 h-3" strokeWidth={2} />
      صالح لمدة:
      <span className="text-text-primary font-medium">
        {hours > 0 && `${hours}س `}
        {String(minutes).padStart(2, "0")}د {String(seconds).padStart(2, "0")}ث
      </span>
    </p>
  );
}
